<?php
// menu_catalog.php - page catalogue generated from header.php menu (Section > Main menu > Sub menu > Page).
// Re-generate / edit when menu items are added to header.php.
return [
    ['Main Menu', 'Main Menu', null, 'index', 'Dashboard'],
    ['Main Menu', 'Master', null, 'company', 'Company'],
    ['Main Menu', 'Master', null, 'branches', 'Branch'],
    ['Main Menu', 'Master', null, 'staff_category', 'Staff Category'],
    ['Main Menu', 'Master', null, 'designations', 'Designations'],
    ['Main Menu', 'Master', null, 'routes', 'Route'],
    ['Main Menu', 'Master', null, 'vehicles', 'Vehicles'],
    ['Main Menu', 'Master', null, 'cash_collectors', 'Cash Collectors'],
    ['Main Menu', 'Master', null, 'emergency_credit_reasons', 'EM Credit Reasons'],
    ['Main Menu', 'Master', null, 'bill_cancel_reasons', 'Bill Cancel Reasons'],
    ['Main Menu', 'Master', null, 'credit_bill_return_reasons', 'Credit Bill Return Reasons'],
    ['Main Menu', 'Master', null, 'field_summary_risk_bill_reasons', 'Field Summary Risk Bill Reasons'],
    ['Main Menu', 'Master', null, 'send_back_cheque_reasons', 'SB Cheques Reasons'],
    ['Main Menu', 'Master', null, 'company_bank_accounts', 'Company Bank Accounts'],
    ['Main Menu', 'Master', null, 'cheque_book_entry', 'Cheque Book Entry'],
    ['Main Menu', 'Master', null, 'ai_settings', 'AI Settings'],
    ['Main Menu', 'Master', null, 'company_letterhead', 'Letter Head'],
    ['Main Menu', 'Master', null, 'stl', 'STL Settings'],
    ['Main Menu', 'Master', null, 'sms_settings', 'SMS Settings'],
    ['Main Menu', 'Master', null, 'backup_settings', 'DB Backup'],
    ['Main Menu', 'Master', null, 'bank_holidays', 'Bank Holidays'],
    ['Main Menu', 'User Master', null, 'users', 'Users'],
    ['Main Menu', 'User Master', null, 'role', 'User Role'],
    ['Main Menu', 'IT', null, 'notifications', 'Notification Center'],
    ['Main Menu', 'AI Analys', null, 'outlet_service_info_upload', 'Outlet Service Information Upload'],
    ['Main Menu', 'AI Analys', null, 'outlet_service_map', 'Map Analysing'],
    ['Management', 'Human Resources', null, 'employees', 'Employees'],
    ['Management', 'Human Resources', null, 'employee_register', 'Employee Register'],
    ['Management', 'Human Resources', 'Leave & Attendance', 'leave_list', 'Leave Application'],
    ['Management', 'Human Resources', 'Leave & Attendance', 'leave_register', 'Leave Register'],
    ['Management', 'Human Resources', 'Leave & Attendance', 'add_attendance', 'Attendance Manual Entry'],
    ['Management', 'Human Resources', 'Leave & Attendance', 'attendance_report', 'Attendance'],
    ['Management', 'Human Resources', 'Leave & Attendance', 'attendance_summary_salary', 'Attendance Summary'],
    ['Management', 'Human Resources', 'Leave & Attendance', 'attendance_monthly_roster', 'Attendance Monthly Roster'],
    ['Management', 'Human Resources', 'Leave & Attendance', 'attendance_import', 'Import Attendance'],
    ['Management', 'Human Resources', 'Leave & Attendance', 'import_to_attendance', 'Import to Attendance'],
    ['Management', 'Human Resources', 'Leave & Attendance', 'biolink', 'Biometric Machine'],
    ['Management', 'Human Resources', 'Leave & Attendance', 'special_working_days', 'Company Holidays'],
    ['Management', 'Human Resources', null, 'payroll_months', 'Payroll Months'],
    ['Management', 'Human Resources', null, 'salary_advance', 'Salary Advance'],
    ['Management', 'Human Resources', null, 'loans', 'Loans'],
    ['Management', 'Human Resources', null, 'sr_fuel_entry', 'SR Fuel Entry'],
    ['Management', 'Human Resources', null, 'dlink_budget_entry', 'MR D Link'],
    ['Management', 'Human Resources', null, 'sr_salary_config', 'Salary Configuration'],
    ['Management', 'Human Resources', null, 'incentive_types', 'Incentive'],
    ['Management', 'Human Resources', 'Salary Sheets', 'sr_salary', 'SR Salary Sheet'],
    ['Management', 'Human Resources', 'Salary Sheets', 'mr_salary', 'MR Salary Sheet'],
    ['Management', 'Human Resources', 'Salary Sheets', 'off_salary', 'Office Staff Salary Sheet'],
    ['Management', 'Human Resources', 'Salary Sheets', 'st_salary', 'Stores Salary Sheet'],
    ['Management', 'Human Resources', 'Salary Sheets', 'cc_salary', 'CC Salary Sheet'],
    ['Management', 'Human Resources', 'Salary Sheets', 'acc_salary', 'ACC Salary Sheet'],
    ['Management', 'Human Resources', 'Salary Sheets', 'salary_excel_generate', 'Total Salary'],
    ['Management', 'Human Resources', 'Salary Sheets', 'salary_reconciliation_yearly', 'Basic Salary Reconcilation'],
    ['Management', 'Human Resources', 'Salary Sheets', 'salary_reconciliation', 'Total Salary Reconcilation'],
    ['Management', 'Human Resources', null, 'epf', 'EPF/ETF Settings'],
    ['Management', 'Human Resources', null, 'epf_batches', 'EPF Report'],
    ['Management', 'Human Resources', null, 'etf_batches', 'ETF Report'],
    ['Management', 'Human Resources', null, 'print_payslips', 'Print Payslips'],
    ['Management', 'Customers', null, 'customers', 'Customers'],
    ['Management', 'Customers', null, 'credit_policy_import', 'Import Credit Policy'],
    ['Vehicle Management', 'Lorry Maintenance', null, 'vehicle_types', 'Vehicle Types'],
    ['Vehicle Management', 'Lorry Maintenance', null, 'vehicle_fuel_log', 'Fuel Log (KM Sheet)'],
    ['Vehicle Management', 'Lorry Maintenance', null, 'vehicle_insurance', 'Insurance'],
    ['Vehicle Management', 'Lorry Maintenance', null, 'vehicle_revenue_license', 'Revenue License'],
    ['Vehicle Management', 'Lorry Maintenance', null, 'vehicle_tyres', 'Tyres'],
    ['Vehicle Management', 'Lorry Maintenance', null, 'vehicle_dag_report', 'Tyre Dag Report'],
    ['Vehicle Management', 'Lorry Maintenance', null, 'vehicle_service_item_types', 'Service Items Creation'],
    ['Vehicle Management', 'Lorry Maintenance', null, 'vehicle_service', 'Service'],
    ['Vehicle Management', 'Lorry Maintenance', null, 'vehicle_repair', 'Repair'],
    ['Vehicle Management', 'Lorry Maintenance', null, 'vehicle_spare_parts', 'Spare Parts Stock'],
    ['Vehicle Management', 'Lorry Maintenance', null, 'vehicle_employee_damage', 'Employee Damage Claims'],
    ['Vehicle Management', 'Vehicle Tracking', null, 'vehicle_schedule', 'Vehicle Schedule'],
    ['Vehicle Management', 'Vehicle Tracking', null, 'position_report_import', 'Position Report Import'],
    ['Vehicle Management', 'Vehicle Tracking', null, 'park_report_import', 'Import Parking Report'],
    ['Vehicle Management', 'Vehicle Tracking', null, 'vehicle_daily_summary', 'Daily Vehicle Summary'],
    ['Vehicle Management', 'Vehicle Tracking', null, 'vehicle_routing_efficiency_report', 'Daily Vehicle Summary Report'],
    ['Vehicle Management', 'Vehicle Tracking', null, 'drive_mileage_report', 'Drive Millage Report'],
    ['Vehicle Management', 'Vehicle Tracking', null, 'parking_report', 'Parking Report'],
    ['Finance', 'Daily Transaction Management', null, 'import_history', 'Create Field Summary'],
    ['Finance', 'Daily Transaction Management', null, 'blacklisted_import_review', 'Blacklisted Import Review'],
    ['Finance', 'Daily Transaction Management', null, 'cancelled_to_field_summary', 'Cancelled → Field Summary'],
    ['Finance', 'Daily Transaction Management', null, 'customer_ledger', 'Customer Ledger'],
    ['Finance', 'Daily Transaction Management', null, 'field_summary_list', 'Field Summary List'],
    ['Finance', 'Daily Transaction Management', null, 'fs_se', 'Field Summary Short/Excess'],
    ['Finance', 'Daily Transaction Management', null, 'unloading_import_history', 'Create Unloading Sheet'],
    ['Finance', 'Daily Transaction Management', null, 'gse_list', 'Good Short/Excess'],
    ['Finance', 'Daily Transaction Management', null, 'reconcile_unloading', 'Unloading Reconcile'],
    ['Finance', 'Daily Transaction Management', null, 'payments_report', 'Payments'],
    ['Finance', 'Daily Transaction Management', null, 'invoices', 'Invoices'],
    ['Finance', 'Daily Transaction Management', null, 'customer_summary', 'Invoices Summary'],
    ['Finance', 'Daily Transaction Management', null, 'cc_cash_deposit', 'CC Cash Deposit (SR)'],
    ['Finance', 'Daily Transaction Management', null, 'cc_cash_deposit_dp', 'CC Cash Deposit (DP)'],
    ['Finance', 'Daily Transaction Management', null, 'bo_cash_deposit', 'BO Cash Deposit (SR)'],
    ['Finance', 'Daily Transaction Management', null, 'bo_cash_deposit_dp', 'BO Cash Deposit (DP)'],
    ['Finance', 'Daily Transaction Management', null, 'grn_report', 'GRN Report'],
    ['Finance', 'Sampath Operation', null, 'sampath_damage_batches', 'Sampath Damage Entry'],
    ['Finance', 'Sampath Operation', null, 'sampath_super_payment', 'Sampath Super Payments'],
    ['Finance', 'Sampath Operation', null, 'sampath_grn_reasons', 'Sampath GRN Reasons'],
    ['Finance', 'Sampath Operation', null, 'sampath_grn_batches', 'Sampath GRN Summary'],
    ['Finance', 'Sampath Operation', null, 'sampath_grn_reconciliation', 'Sampath GRN Reconcilation'],
    ['Finance', 'Sampath Operation', null, 'sampath_stock_reconciliation', 'Sampath Stock Reconcilation'],
    ['Finance', 'Sampath Operation', null, 'unilever_purchase_import', 'Unilever Purchase Import'],
    ['Finance', 'Sampath Operation', null, 'unilever_items_return', 'Unilever Items Return'],
    ['Finance', 'U Shop', null, 'ushop_items_import_history', 'U Shop Opening Stock Entry'],
    ['Finance', 'U Shop', null, 'ushop_invoice_history', 'U Shop Invoices'],
    ['Finance', 'U Shop', null, 'monthly_invoice_summary', 'Monthly Summary'],
    ['Finance', 'U Shop', null, 'ushop_letter_categories', 'Letter Categories'],
    ['Finance', 'U Shop', null, 'ushop_payment_invoice_list', 'Payment Invoice Creation'],
    ['Finance', 'U Shop', null, 'ushop_letter_create', 'Letter Creation'],
    ['Finance', 'U Shop', null, 'ushop_payment_reconciliation', 'Payment Reconcilation'],
    ['Finance', 'U Shop', null, 'visa_reconciliation', 'Visa Card Reconcilation'],
    ['Finance', 'U Shop', null, 'ushop_visa_reconciliation_report', 'Visa Reconcilation Report'],
    ['Finance', 'U Shop', null, 'ushop_monthly_category_report', 'Monthly Report'],
    ['Finance', 'U Shop', null, 'ushop_dashboard_report', 'U Shop Dashboard'],
    ['Finance', 'Inventory Management', null, 'current_stock_history', 'Daily Current Stock'],
    ['Finance', 'Inventory Management', null, 'invoice_wise_sales_history', 'Daily Secondary Stock'],
    ['Finance', 'Inventory Management', null, 'primary_invoice_wise_sales_history', 'Daily Pre Secondary Stock'],
    ['Finance', 'Inventory Management', null, 'physical_stock_count_upload', 'Physical Stock Count'],
    ['Finance', 'Credit Bill Management', null, 'credit_bill_summary2', 'Credit Bill Summary'],
    ['Finance', 'Credit Bill Management', null, 'credit_bill_issue', 'Credit Bill Issue'],
    ['Finance', 'Credit Bill Management', null, 'credit_notes_list', 'Credit Notes'],
    ['Finance', 'Credit Bill Management', null, 'payments', 'Credit Payments'],
    ['Finance', 'Credit Bill Management', null, 'bulk_credit_bill_upload', 'Upload Credit Bills'],
    ['Finance', 'Credit Bill Management', null, 'emergency_credit_bill_upload', 'Upload Em.Credit Bills'],
    ['Finance', 'Credit Bill Management', null, 'import_credit_notes', 'Import Bulk Credit Note'],
    ['Finance', 'Credit Bill Management', null, 'sr_code_bulk_update', 'Import Bulk SR Code Change'],
    ['Finance', 'Credit Bill Management', null, 'credit_bill_beat_update', 'Import Bulk SR Code Change (T Code Wise)'],
    ['Finance', 'Cheque Management', null, 'cheques', 'Cheque Register'],
    ['Finance', 'Cheque Management', null, 'return_cheques', 'Payment-Returned Chq.'],
    ['Finance', 'Cheque Management', null, 'return_charges', 'Payment-CRN Charges'],
    ['Finance', 'Cheque Management', null, 'sentback_cheques', 'Payment-Sent Back Chq.'],
    ['Finance', 'Cheque Management', null, 'cheque_deposit_letter', 'Cheque Deposit Letters'],
    ['Finance', 'Cheque Management', null, 'stl_letters', 'STL Request Letters'],
    ['Finance', 'Cheque Management', null, 'stl_settlement', 'STL Settlement'],
    ['Finance', 'Cheque Management', null, 'stl_forecasting', 'STL Forecasting'],
    ['Finance', 'Cheque Management', null, 'cheque_aging_report', 'Cheque Aging Report'],
    ['Finance', 'Cheque Management', null, 'cheque_mode_report', 'Cheque Mode Report'],
    ['Finance', 'Cheque Management', null, 'cheque_mode_report_dp', 'Cheque Mode Report (DP)'],
    ['Finance', 'Cheque Management', null, 'deposit', 'Cheque Reconciliation'],
    ['Finance', 'Cheque Management', null, 'manual', 'Manual Reconciliation'],
    ['Finance', 'Cheque Management', null, 'bulk_cheque_verify', 'Import Cheques'],
    ['Finance', 'Customer Ledger', null, 'primary_invoices', 'Primary Invoices'],
    ['Finance', 'Customer Ledger', null, 'purchase_return_summary_report', 'Primary Sales Return'],
    ['Finance', 'Customer Ledger', null, 'damaged_claim', 'Damaged Claim'],
    ['Finance', 'Customer Ledger', null, 'pi_other_adjustments', 'Other Adjustments'],
    ['Finance', 'Customer Ledger', null, 'pi_reconciliation', 'Primary Invoices Reconciliation'],
    ['Finance', 'Customer Ledger', 'Import', 'damage_proposal_history', 'Damage Shortage Proposal Report'],
    ['Finance', 'Customer Ledger', 'Import', 'purchase_return_history', 'Product Wise Purchase Return'],
    ['Finance', 'Customer Ledger', 'Import', 'purchase_return_register_history', 'Purchase Return Register'],
    ['Finance', 'Customer Ledger', 'Import', 'ulcl_history', 'Unilever Customer Ledger'],
    ['Finance', 'Vendor Ledger', null, 'daily_scheme_discounts', 'Daily Scheme Discounts'],
    ['Finance', 'Vendor Ledger', null, 'scheme_discount_receivable', 'Scheme Discount'],
    ['Finance', 'Vendor Ledger', null, 'free_issue_cc_receivable', 'Free Issues'],
    ['Finance', 'Vendor Ledger', null, 'debit_note', 'Muthupalasa BP Claims'],
    ['Finance', 'Vendor Ledger', null, 'promoters_salary_cl', 'Promoters Salary'],
    ['Finance', 'Vendor Ledger', null, 'sr_incentive_cc', 'SR Incentive'],
    ['Finance', 'Vendor Ledger', null, 'sscl_vat', 'SSCL &amp; VAT'],
    ['Finance', 'Vendor Ledger', null, 'dal', 'Drivers &amp; Loyalty'],
    ['Finance', 'Vendor Ledger', null, 'others_cc', 'Others'],
    ['Finance', 'Vendor Ledger', null, 'cheque_acknowledgments', 'Acknowledgment'],
    ['Finance', 'Vendor Ledger', 'Import', 'customer_claim', 'Customer Claim Certificate Import'],
    ['Finance', 'Vendor Ledger', 'Import', 'billwise_scheme', 'Bill Wise Scheme Analysis Import'],
    ['Finance', 'Bank Reconciliation', null, 'bank_account_dashboard', 'Bank Account Dashboard'],
    ['Finance', 'Bank Reconciliation', null, 'bank_statements', 'Import Bank Statement'],
    ['Finance', 'Bank Reconciliation', null, 'bank_datewise_transactions', 'Date-wise Transactions'],
    ['Finance', 'Bank Reconciliation', null, 'bank_recon_reasons', 'Reconcile Reasons'],
    ['Finance', 'Bank Reconciliation', null, 'cc_deposit_dp_bank_recon', 'Deposit Reoncilation'],
    ['Finance', 'Bank Reconciliation', null, 'cheque_reconciliation', 'Cheque Reconcilation'],
    ['Finance', 'Bank Reconciliation', null, 'pi_cheque_bank_recon', 'Unilver Payment Reconcilation'],
    ['Finance', 'Bank Reconciliation', null, 'unilever_reconcile', 'Reimbursment Reconcilation'],
    ['Finance', 'Bank Reconciliation', null, 'ca_issued_cheque_bank_recon', 'Customer Claims Reconcilation'],
    ['Finance', 'Bank Reconciliation', null, 'stl_loan_grant_recon', 'STL Loan Granted Reconcilation'],
    ['Finance', 'Bank Reconciliation', null, 'stl_loan_settle_bank', 'STL Settlement Reconcilation'],
    ['Finance', 'Bank Reconciliation', null, 'expense_payment_bank_recon', 'Expense Reconcilation'],
    ['Finance', 'Accounts', null, 'mybos_accounts', 'MYBOS Accounts'],
    ['Finance', 'Accounts', null, 'budget', 'Budget'],
    ['Finance', 'Accounts', null, 'roi', 'ROI'],
    ['Finance', 'Accounts', null, 'expense_category', 'Expense Categories'],
    ['Finance', 'Accounts', null, 'expenses', 'Expenses'],
    ['Finance', 'Accounts', null, 'expense_payments', 'Expense Payments'],
    ['Finance', 'Accounts', null, 'cash_float', 'Cash Floats'],
    ['Reports', 'Reports', null, 'credit_aging_report', 'Credit Aging Report'],
    ['Reports', 'Reports', null, 'rep_wise_credit_aging_report', 'Credit Aging Report (Rep)'],
    ['Reports', 'Reports', null, 'customer_credit_risk_report', 'Customer Risk'],
    ['Reports', 'Reports', null, 'route_wise_credit_summary', 'Route Wise Credit Summary'],
    ['Reports', 'Reports', null, 'market_credit_report', 'Market Credit Report'],
    ['Reports', 'Reports', null, 'cheque_aging_report_group', 'Cheque Aging Report Group'],
    ['Reports', 'Reports', null, 'blacklisted_customers_report', 'Customer Blacklist Report'],
    ['Reports', 'Reports', null, 'risk_customer_bills_report', 'Risk Customer Bills Report'],
    ['Reports', 'Reports', null, 'credit_bill_scan_report', 'Credit Bill Upload Report'],
    ['Reports', 'Reports', null, 'emergency_credit_bill_upload_report', 'Em.Credit Bill Upload Report'],
    ['Reports', 'Reports', null, 'final_report', 'Day End Full Report-T'],
    ['Reports', 'Reports', null, 'full_report', 'Full Report (SR)'],
    ['Reports', 'Reports', null, 'full_report_dp', 'Full Report (DP)'],
    ['Reports', 'Reports', null, 'sum', 'Collection Summary (SR)'],
    ['Reports', 'Reports', null, 'cash_collection_by_delivery_person', 'Collection Summary (DP)'],
    ['Reports', 'Reports', null, 'cc_report', 'Full Cash Collection (DP)'],
    ['Reports', 'Reports', null, 'cash_shortage_employee_report', 'Cash Shortage Report (SR)'],
    ['Reports', 'Reports', null, 'cash_shortage_employee_report_dp', 'Cash Shortage Report (DP)'],
    ['Reports', 'Reports', null, 'fs_shortage_charge_report', 'Field Summary Shortage Charge Report'],
    ['Reports', 'Reports', null, 'bank_deposit_summary', 'Bank Deposit Summary (SR)'],
    ['Reports', 'Reports', null, 'bank_deposit_summary_dp', 'Bank Deposit Summary (DP)'],
    ['Reports', 'Reports', null, 'bank_deposit_summary_slip', 'Bank Deposit Summary (Slip Wise SR)'],
    ['Reports', 'Reports', null, 'bank_deposit_summary_slip_dp', 'Bank Deposit Summary (Slip Wise DP)'],
    ['Reports', 'Reports', null, 'item_shortage_employee_report', 'Good/Short Excess Report'],
    ['Reports', 'Reports', null, 'employee_shortage_report', 'Employee Wise GSE Report'],
    ['Reports', 'Reports', null, 'daily_gse_report', 'Daily GSE Report'],
    ['Reports', 'Reports', null, 'unloading_monthly_summary', 'Item Wise GSE Summary'],
    ['Reports', 'Reports', null, 'ccf_report', 'CCF Report (DP &amp; SR)'],
    ['Reports', 'Reports', null, 'daily_delivery_monitor', 'Daily Delivery Monitoring Report'],
    ['Reports', 'Reports', null, 'customer_claim_report', 'Customer Claim Report'],
    ['Reports', 'Reports', null, 'profile', 'Profile'],
    ['Reports', 'Reports', null, 'settings', 'Settings'],
    ['Reports', 'Reports', null, 'help', 'Help'],
    ['Reports', 'Reports', null, 'logout', 'Logout'],
];
